CREATE TABLE IF NOT EXISTS availabilities (
  id          VARCHAR(50) PRIMARY KEY,
  doctor_id   INT NOT NULL,
  day_of_week INT NOT NULL,
  start_time  VARCHAR(5) NOT NULL,
  end_time    VARCHAR(5) NOT NULL,
  available   BOOLEAN NOT NULL,
  booked      BOOLEAN NOT NULL DEFAULT 0,
  created_at  DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at  DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  FOREIGN KEY (doctor_id) REFERENCES doctors(id) ON DELETE CASCADE
);
